[debug]
address = "127.0.0.1"
port = 8008

[default]
address = "0.0.0.0"
port = 443

#[default.tls]
#key = "/usr/local/etc/letsencrypt/live/my.domain.com/privkey.pem"
#certs = "/usr/local/etc/letsencrypt/live/my.domain.com/fullchain.pem"

[limits]
form = "4 kB"
json = "4 kB"
